dataset:
  target: dataset.LRHRRef.LRHRRefDataset
  params:
    # Path to the file list.
    dataroot: /mnt/massive/wangce/SGDM/dataset/S2-Arcgis/train

    l_resolution: 16
    r_resolution: 256
    split: "train"
    data_len: -1
    use_txt: true
    style_path: /mnt/massive/wangce/SGDM/dataset/S2-Arcgis/train/hr_256

data_loader:
  batch_size: 16
  shuffle: false
  num_workers: 16
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
